@echo off
set PY_VERSION=%1
set EPVERSION_FILE=..\..\include\EmbPython\SprEPVersion.h

call CurrEPVersion.bat %1

if %PY_VERSION%==%CURR_PY_VERSION% (
echo "Do Nothing."
) else (
echo "Set New Version."

echo // *** AUTOMATICALLY CREATED ***      >  %EPVERSION_FILE%
echo // *** DO NOT EDIT THIS FILE ***      >> %EPVERSION_FILE%
echo // Python Version for Embedding       >> %EPVERSION_FILE%
echo #define EMB_PYTHON_VER %PY_VERSION%   >> %EPVERSION_FILE%

echo @echo off                             > CurrEPVersion.bat
echo set CURR_PY_VERSION=%PY_VERSION%      >> CurrEPVersion.bat
)


