// *** AUTOMATICALLY CREATED ***                                  
// *** DO NOT EDIT THIS FILE ***                                  
// Python Version for Embedding                                   
#define EMB_PYTHON_VER 32                               
#define PYTHON_H_REL  "../../include/Python32/Python.h" 
#define PYTHON_H_PATH <Python32/Python.h>             
