// *** AUTOMATICALLY CREATED ***                                  
// *** DO NOT EDIT THIS FILE ***                                  
// Python Version for Embedding                                   
#define EMB_PYTHON_VER 33                               
#define PYTHON_H_REL  "../../include/Python33/Python.h" 
#define PYTHON_H_PATH <Python33/Python.h>             
