#!/usr/local/bin/python
# -*- coding: utf-8 -*-
# ==============================================================================
#  SYNOPSIS:
#	python CheckClosedSrc.py
#
#  DESCRIPTION:
#	"SprDefs.h"からインクルードされるファイル"SprUseClosedSrcOrNot.h"を、
#	次の条件で作成する。
#
#	"core/include"に既に"SprUseClosedSrcOrNot.h"が存在しないときに限り、
#	次の内容を"core/include/SprUseClosedSrcOrNot.h"として書き出す。
#	    "#define USE_CLOSED_SRC"	"Springhead/closed"が存在する
#	    "#undef USE_CLOSED_SRC"	"Springhead/closed"が存在しない
#
# ==============================================================================
#  Version:
#     Ver 1.00	 2019/01/08 F.Kanehori	初版
#     Ver 1.01	 2019/04/01 F.Kanehori	Python library path 検索方法変更.
#     Ver 2.00	 2020/04/09 F.Kanehori	方針の全面変更 (DESCRIPTION参照)
#     Ver 2.01	 2020/04/12 F.Kanehori	Bug fix.
#     Ver 2.10	 2020/05/12 F.Kanehori	再度方針の全面変更 (DESCRIPTION参照)
#     Ver 2.10.1 2020/11/11 F.Kanehori	不要なコードの削除
#     Ver 2.11   2021/02/17 F.Kanehori	Python 2.7 対応
# ==============================================================================
from __future__ import print_function
version = '2.11'

import sys
import os
import shutil
from optparse import OptionParser

# ----------------------------------------------------------------------
#  Constants
#
prog = sys.argv[0].split(os.sep)[-1].split('.')[0]

# ----------------------------------------------------------------------
#  Import Springhead python library.
#
from FindSprPath import *
spr_path = FindSprPath(prog)
libdir = spr_path.abspath('pythonlib')
sys.path.append(libdir)
from TextFio import *
from Proc import *
from Error import *

# ----------------------------------------------------------------------
#  Directories
#
sprtop = spr_path.abspath()
incdir = spr_path.relpath('inc')
closed = '%s/closed' % sprtop

# ----------------------------------------------------------------------
#  Files
#
header_file = 'SprUseClosedSrcOrNot.h'
tmp_file = header_file + '.tmp'

# ----------------------------------------------------------------------
#  オプションの定義
#
usage = 'Usage: %prog [options]'
parser = OptionParser(usage = usage)
parser.add_option('-v', '--verbose', dest='verbose',
			action='count', default=0,
                        help='set verbose count')
parser.add_option('-V', '--version', dest='version',
			action='store_true', default=False,
                        help='show version')

# ----------------------------------------------------------------------
#  コマンドラインの解析
#
(options, args) = parser.parse_args()
if options.version:
        print('%s: Version %s' % (prog, version))
        sys.exit(0)
if len(args) != 0:
	Error(prog).error('incorrect number of arguments')
	Proc().execute('python %s.py -h' % prog).wait()
	sys.exit(0)

verbose = options.verbose

# ----------------------------------------------------------------------
#  処理開始
#	
cwd = os.getcwd()
os.chdir(incdir)
if verbose:
	print('%s: cwd: %s' % (prog, os.getcwd().replace(os.sep, '/')))

# ----------------------------------------------------------------------
#  ファイル "SprUseClosedSrcOrNot.h" が存在したら何もしない
#
if os.path.exists(header_file):
	if verbose:
		print('%s: file exists. bothing to do.' % prog)
	#  処理終了
	os.chdir(cwd)
	sys.exit(0)

# ----------------------------------------------------------------------
#  ヘッダファイルの内容を決める
#
macro = r'#undef USE_CLOSED_SRC'
if os.path.exists(closed):
	if os.path.isdir(closed):
		macro = r'#define USE_CLOSED_SRC'
	else:
		print('%s: Warning: "%s" exists but not a directory' % (prog, closed))
lines = []
lines.append(r'// This file is generated by Springhead system.')
lines.append(r'')
lines.append(r'// Use Springhead/closed source or not.')
lines.append(macro)

# ----------------------------------------------------------------------
#  ファイルに書き出す
#
fio = TextFio(header_file, 'w')
if fio.open() != 0:
	Error(prog).error('can not open file "%s"' % header_file)
if fio.writelines(lines) != 0:
	Error(prog).error('write failed on file  %s"' % header_file)
fio.close()
print('%s: "%s" written with "%s"' % (prog, header_file, macro))

# ----------------------------------------------------------------------
#  処理終了
#	
os.chdir(cwd)
sys.exit(0)

# end: CheckClosedSrc.py
