//
// Copyright (c) 1999 by Sigma Itec Inc.
//
// Tokin 3D Motion Sensor COM DLL
//
// YYYY/MM/DD VV/LL :Comment
// 1999/05/25 01/00 :Create		// 1999.05.25 add sit(v0120-0002)


#ifndef __TKINPUTDEF_H_
#define __TKINPUTDEF_H_


// ----------------------------------------------------------------------
// ÉäÉ^Å[ÉìèÓïÒ
// ----------------------------------------------------------------------
#define TK3DERR_OK                      0x00000000
#define TK3DERR_FATAL_ERROR             0x80000000
#define TK3DERR_NON_DEVICE              0x80000001
#define TK3DERR_NOT_SETADSTDDATA        0x80000100
#define TK3DERR_NOT_POLLING             0x80000200
#define TK3DERR_NOT_DATAUPDATE          0x80000400
#define TK3DERR_INIT_CALC               0x80000800
#define TK3DERR_DATA_OVERFLOW           0x80000C00
#define TK3DERR_NON_ADSTDDATA           0x80001000	// 1999.05.19 add sit(v0120-0001)
#define TK3DERR_NOT_OPEN_MOUSE_DRIVER   0x80010000



#endif //__TK3DSENSOR_H_
