#  File: Makefile.NameManager
			
INIFILE	= NameManager.ini
SCRIPT	= NameManager.py
TARGET	= NameManager.bat

all:	$(TARGET)

$(TARGET):	$(INIFILE) $(SCRIPT)
		GoPython $(SCRIPT)

clean:		
		del $(TARGET) >NUL 2>&1

$(INIFILE):			

$(SCRIPT):			

