/**	
	@mainpage <a href="http://springhead.info">Springhead</a>
	<center>
	@!JA長谷川晶一，岡田直樹，田崎勇一，市川宙，藤井伸旭，白井暁彦，田上信一郎
	@!EN Shoichi HASEGAWA, Naoki Okada, Yuuichi TAZAKI, Hirosi ICHIKAWA, Nobuaki FUJII,
		Akihiko SHIRAI, Shinichirou TAGAMI
	@!*
	<br>
	</center>

	@section SpringheadAbstract @!JA 概要 @!EN Abstract
	@!JA
	Springheadは東工大，佐藤・小池研助手の長谷川晶一が中心に開発している
	バーチャルリアリティ開発環境の開発コードネームです．<br>
	力覚提示装置の制御と物理シミュレータが統合されているので，力覚提示装置で
	物理則を持つVR空間とインタラクションできます．<br>
	@!EN
	Springhead is a code name of a virtual reality software
	development environment, which is being developed by Shoichi Hasegawa,
	a research associate for Sato & Koike Lab in Tokyo Institute of Technology.<br>
	Using Springhead, you can interact with virtual world with physics law
	via haptic interfaces. Springhead has rigid body motion simulator
	and haptic device controller.
	@!*

	@section SpringheadDocument @!JAこのドキュメントについて @!EN About this document
	@!JA
	このドキュメントはDoxygenというツールを使ってソースコードから生成しています．
	このページも Springhead/src/Spinghead.h から生成しました．<br>
	- Springheadをはじめて使用する場合は，まず，<A href="../../ReadMe.JA.txt">
	ReadMe.JA.txt</A>を参照してください．
	- <A href="http://springhead.info/wiki">SpringheadのWiki</A>にもドキュメントがあります．

	<A href="../../SpringheadDoc.bat">Springhead/src/SpringheadDoc.bat</A>
	を実行するとこのドキュメントを生成することができます．
	ドキュメントに不具合がある場合は，
	ソースファイルのコメントにバグがあるかも知れません．
	<A href="../../doxygen.log">doxygen.log</A>を見てください．<br>
	doxygenについてはdoxygenのホームページを参照してください．<br>
	@!EN
	This document is generated by Doxygen from soruce code.
	This page is genarated from Springhead/src/Spinghead.h. <br>
	- Please read <A href="../../ReadMe.EN.txt">ReadMe.EN.txt</A> first.<br>
	- There are some documents on <A href="http://springhead.info/wiki">Wiki for Springhead</A>.

	You can generate document by executing <A href="../../SpringheadDoc.bat">Springhead/src/SpringheadDoc.bat</A>.
	If there is some problem in document, Some comments in soruce files may have
	bugs In such cases, please see <A href="../../doxygen.log">doxygen.log</A>.<br>
	Please see docxygen's home page for the detail of doxygen. <br>
	@!*

	@section SpringheadArchitecture @!JA 構成 @!EN Architecture @!*
	@!JA 次のような構成になっています．
	@!EN Following is architecture of Springhead．
	@!*

	@subsection utilityLibs	@!JA C++やDirectXなどを便利に使うための汎用ライブラリ
							@!EN Generic utilities for C++ or DirectX.
							@!*
	- @ref Base
		@!JA C++を便利にするための基本的なライブラリ．<br>
		@!EN Basic utility library for C++.<br>
		@!* Classes: @ref Affine @ref UTRef ...
	- @ref WinBasis
		@!JA Windows.hの問題点を解消するためのライブラリ．<br>
			 構成間の相違の吸収，面倒なAPIのラッパクラス<br>
		@!EN Fixing for Windows.h's problem.<br>
			 Absorbers for difference in configurations.
			 Wrappers for complicated APIs.<br>
		@!* Classes: Spr::WBMMTimer Spr::WBComStream Spr::WBSocket Spr::WBGuid ...
	- @ref WinDX
		@!JA DirectXを使う上での面倒を解消するためのライブラリ．<br>
		@!EN Wrappers for DirectX<br>
		@!* Classes: Spr::WXUnknown Spr::WXInterface Spr::WXDXError Spr::WXD3D8Device

	@subsection functionLibs @!JA シーングラフやファイル入出力などSpringheadの機能を構成するライブラリ
		@!EN Libraries which create the functions of the springhead such as, scene graphs or file loaders and savers.
	- @ref SceneGraph
		@!JA シーングラフを作るクラスたち<br>
		@!EN Scene Graph<br>
		@!* Classes： Spr::SGFrame Spr::SGVisual ... @ref Implementation is done by ImpD3D.
	- @ref FileIO
		@!JA ファイル入出力を楽にするクラスたち．<br>
		Spr::FIDocNode のツリーからなるドキュメントを操作することで
		ファイルの入出力を行う．実装は @ref @!JA ImpD3D などで行う．
		@!EN File input/output helper classes.<br>
		File input/output can be done by operating documents,
		which consist from tree of Spr::FIDocNode.
		Implimentations are done by inherited package like @ref @!EN ImpD3D.
		@!*
	- @ref ImpD3D
		@!JA Direct3D を用いた実装．<br>
		Direct3Dを用いて，レンダラとファイル入出力を実現する．
		@!EN Implementation with Direct3D,<br>
			Implementation of rendering and file input/output with Direct3D.
		@!*
	@subsection springheadSamples @!JA サンプルプログラム @!EN Sample programs @!*
	- @ref MFCD3DDyna	物理シミュレーションとグラフィックのデモ
	- @ref Spidar 力覚インタフェースSPIDARで壁を提示するだけのサンプル．物理，グラフィックなし．
	- @ref DynaHaptic	力覚インタフェース＋物理シミュレーション

	@section SpringheadPoint @!JAチュートリアル  @!EN Tutorial @!*
	- @ref TutorialVC

	@section SpringheadHack @!JAソースコードハックのしかた @!EN How to hack the source @!*
	
	- @!JA まず，サンプルの @ref DynaHaptic を見て大まかな処理の流れを
	  つかんでください．
	  @!EN See the sample program of @ref DynaHaptic to understand
	  main flow of the execution.@!*
	- @!JA 次に，見慣れないクラスや書き方が目に付くと思いますので，
	  それらを @ref Base, @ref WinBasis, @ref WinDX を参照して確認してください．
	  @!EN You'll find unfamiliar classes and idioms.
	  	Please check them, by refering @ref Base, @ref WinBasis, @ref WinDX.@!*
	- @!JA 大まかな構造が知りたいときは，
	  <A href="../SceneGraph/class.ppt">クラス・パッケージ図(目標)</A>
	  や<A href="inherits.html">実際のクラス図</A>を見てください．
	  @!EN If you want to know general structure, see
	  <A href="../SceneGraph/class.ppt">classes and pakages diagram (A desk plan)</A>
	  or <A href="inherits.html">real class diagram</A>.@!*
	- @!JA 処理の詳細が知りたくなったら， @ref ImpD3D を見てください．Direct3D
	  を呼び出しているところがあります．
	  @!EN If you want to know detail of execution, see @ref ImpD3D.
	   That calls DirectX APIs.@!*
	- @!JA 力覚提示装置などのヒューマンインタフェース(@ref HIS)は，
	  デバイス(@ref Device)と分離してあります．
	  これにより，たとえばSpidarのモータドライバを取り替えても，
	  アルゴリズム部分(@ref HIS)は書き換えなくてすむようになっています．
	  @!EN Human interfaces(@ref HIS) such as haptic interfaces
	  are decoupled from device(@ref Device).
	  Therefore, for example, you can change SPIDAR's motor driver with 
	  out rewriting algirithum part(@ref HIS).@!*
	
	@section misc	@!JA雑多なこと @!EN Miscellany@!*
	@subsection MultiLanguageDocument @!JAドキュメントの多国語対応 @!EN Treatment of multiple language document
	@!JA
	ドキュメントの多国語対応は次のように行います．
	- 最初は母国語でコメントを記入する．
	- 別の言語のコメントを足すときは，言語識別タグを入れる．(ソースコードには
	全言語のコメントが記入される．)
	- ドキュメント生成時に doxygen が読む前に，ソースコードにフィルタを掛ける
	  ことで，必要な必要な言語のマニュアルを生成する．
	言語識別用のタグは @@と!と2文字の言語識別文字列(JAが日本語，ENが英語)です．
	（続けて書くとフィルタされてしまうので分けて書いています)
	タグは次の@@まで有効です．
	<A href="../../SpringheadJA.doxy">Springhead/src/SpringheadJA.doxy</A>
	の INPUT_FILTER を書き換えることで，生成するドキュメントの言語を選択できます．

	@!EN
	Following is how to make multi-language documents;
	- At first, write comment in your mothor tange.
	- When writting in other language, insert language identication tag.
	  (So, the source code will have comments in all languages.)
	- In document generation, we can use filter to create a document in proper
	  language.
	The language identification tag is @@ ! and language id of two characters
	(JA is japanese and EN is english).
	(It should be no space. I can't write real tag because it will be filtered.)
	Tags affect to next @@.
	By changing INPUT_FILTER in 
	<A href="../../SpringheadEN.doxy">Springhead/src/SpringheadEN.doxy</A>
	you can choose language of document to generate.

	@section contanct @!JA連絡先
	長谷川 晶一 <hase@hi.pi.titech.ac.jp>
	東京工業大学 精密工学研究所          〒226-8503 横浜市緑区長津田町 4259
	佐藤・小池研究室
	@!EN Contact
	Shoichi HASEGAWA<hase@hi.pi.titech.ac.jp>
	Sato & Koike group, Precision and Intelligence Lab,
	Tokyo institute of technology,
	4259 Nagatsuta-cho Midori-ku Yokohama-shi Kanagawa-ken Japan, 226-8503.
	@!*
*/

/**	@!JA Springheadの名前空間．本来はパッケージ単位で名前空間を定義すべきだが，
	Visual C++ の名前空間にやっかいなバグがあるので，ひとつの名前空間に
	すべてを入れている．
	@!EN namespace for Springhead. 
	*/
namespace Spr{
}
